# Generated by Django 4.0.2 on 2022-02-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_title_description_title_sold_title_types_title_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
